# Generated by Django 6.1 on 2026-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'created_at'],
                               name='xpevent_user_created_idx')),
    ]
