# Generated by Django 6.1 on 2026-08-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_challenge'),
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('best_score', models.FloatField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.sign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sign', 'lesson')},
            },
        ),
    ]
