# Generated by Django 6.1 on 2026-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_signprogress'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'created_at'],
                               name='attempt_user_created_idx')),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'sign'],
                               name='attempt_user_sign_idx')),
    ]
