# Generated by Django 6.0.6 on 2026-06-25 08:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet'), ('word', 'Word'), ('phrase', 'Phrase'), ('mixed', 'Mixed')], default='alphabet', max_length=20)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order_index', models.IntegerField(default=0)),
                ('required_level', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet'), ('word', 'Word'), ('phrase', 'Phrase')], default='alphabet', max_length=20)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reference_landmarks', models.JSONField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True)),
                ('xp_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LessonSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_signs', to='content.lesson')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_signs', to='content.sign')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('lesson', 'sign')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='signs',
            field=models.ManyToManyField(blank=True, through='content.LessonSign', to='content.sign'),
        ),
    ]
